'''This file is for playing the music'''
from os import environ
environ['PYGAME_HIDE_SUPPORT_PROMPT'] = '1'

import pygame
import click
import sys, os

def resource_path(path):
    if hasattr(sys, '_MEIPASS'):
        return os.path.join(sys._MEIPASS, path)
    return path

@click.command(help="Play a MIDI file generated by 'swar musicfy'")
@click.argument('file', required=False)
def play(file: str = None):
    """Play a .mid file with pygame. Defaults to 'swar.mid' if no file is given."""
    pygame.init()
    pygame.mixer.init()

    try:
        filename = f"{file}.mid" if file else "swar.mid"
        click.echo(f"Playing '{filename}' ...")
        pygame.mixer.music.load(resource_path(filename))

        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    except pygame.error as e:
        click.echo(f"Error: {e}")
        click.echo("No musical file. Please create with: swar musicfy [text] --output [filename]")

