[package]
name = "catos"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
crossterm = "0.27"
dirs = "4.0"
regex = "1"